### ISSUE TITLE
copyright

### ISSUE THREAD

**Issue by sils** [coala-analyzer/coala-vim#1]
@hypothesist is https://github.com/coala-analyzer/coala-vim/blob/master/LICENSE#L3 correct?

**Comment by adtac** [comment]
Actually, I'm not really sure about the licenses. Just put MIT without giving it much thought. Should it be anything else? I'd be happy to use whatever coala uses globally

**Comment by sils** [comment]
coala uses AGPL

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-02 20:55 GMT+01:00 Adhityaa Chandrasekar notifications@github.com:
